---
- name: Install, start, and enable Apache web server
  hosts: webservers
  become: yes

  vars:
    git_repo: "https://github.com/Sensini7/Host-a-Secure-Static-Website-On-S3-Bucket-With-Cloudfront-And-Route53.git"
    git_branch: "main"
    html_file: "index.html"

  tasks:
  - name: Update target servers
    yum:
      name: '*'
      state: latest
    when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

  - name: Install Apache
    yum:
      name: httpd
      state: present

  - name: Start Apache
    service:
      name: httpd
      state: started

  - name: Enable Apache at boot time
    service:
      name: httpd
      enabled: yes

  - name: Install Git
    yum:
      name: git
      state: present

  - name: Clone repository
    git:
        repo: "{{ git_repo }}"
        dest: "/tmp/repo"
        version: "{{ git_branch }}"
        clone: yes
        force: yes

  - name: Move HTML file to Apache directory
    command: mv "/tmp/repo/{{ html_file }}" "/var/www/html/{{ html_file }}"

  - name: Delete cloned repository
    file:
      path: /tmp/staticwebsite
      state: absent

  - name: Restart Apache
    service:
      name: httpd
      state: restarted
